### ISSUE TITLE
Issue with connection draining and the services API

### ISSUE THREAD

**Issue by jasonmccallister** [nats-io/nats.go#1228]
### Defect

When using a `micro.Service` created with a custom Go library and running a `docker-compose.yaml` with a NATS server, calling `RequestMsgWithContext` with a new `micro.Service` caused a `nats.ErrNoResponders` error. The suggested example in the README was to use `nc.Drain()`, but calling `defer nc.Drain()` caused the service to not respond.

### Solution

The issue could be resolved by removing the line `defer nc.Drain()`. It seems that this line caused the service to not respond.

#### Versions of `nats.go` and the `nats-server` if one was involved:

nats.go: v1.24.0
nats-server: v2.9.11

#### OS/Container environment:

macOS
Docker Desktop

#### Steps or code to reproduce the issue:

**Requester**

```
// connection
msg, err := nc.RequestMsgWithContext(r.Context(), &nats.Msg{
	Subject: upstream.Subject,
	Data:    event,
})
if err != nil {
	if err == nats.ErrNoResponders {
		log.Fatal(err)
	}
}
```

**Responder**

```
nc, err := nats.Connect(nats.DefaultURL)
if err != nil {
	logger.WithError(err).Fatal("unable to connect to the NATS server")
}
defer nc.Drain()
	
if _, err := micro.AddService(nc, micro.Config{
	Name: subj,
	Endpoint: &micro.EndpointConfig{
		Subject: subj,
		Handler: micro.ContextHandler(ctx, serv.Handle),
	},
	Version:     "0.9.0",
}); err != nil {
	logger.WithError(err).Error("unable to add the service to nats")
}
	
runtime.Goexit()		
```

**Comment by jnmoyne** [comment]
This looks like the expected behavior to me and not a bug. 

Calling Drain() on a connection drains the connection and then closes it (which means any subscriptions made using that connection also get stopped). 

When you call that goExit() it will then do the deferred Drain() and therefore close the connection right there and then and therefore your service's subscription also gets stopped and therefore your service stops being served (there is no process still subscribing to the service's request subject (as the error message indicates)).

**Comment by jasonmccallister** [comment]
It does make sense, but I think I was following the examples here and that is what caused the confusion: https://github.com/nats-io/nats.go#basic-usage
