### ISSUE TITLE
new jetstream interface. consistent user interface for streams and consumers

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1320]
Who doesn't the create/update stream interface follow the same pattern as #1300 defines for stream (three explicit methods instead of  one upsert and one update)?

**Comment by tpihl** [comment]
My understanding, looking for the simplest to read code, would "assume" in the case of creating streams/consumers

Create<something> should fail if there is a something already existing, unless it is identical to what we try to create (declarative idempotent create). It cannot be used to reset startpoint, but it must state the exact same start-point as the existing something to be idempotent.

Update<something> should fail if the something didn't exists. This should preferably not receive a full datastruct since it's very hard to distinguish between zerovalue as don't change and zerovalue as set-to-zero. An update must consider whats already there, so it's kind of the opposite of Create (is it Imperative and not idempotent, and hence also may have race issues)

CreateOrUpdate<something> is the worst of both since it's declarative without any regards to what may already exist (not idempotent) and probably the one with the highest risk to unintentional overwrite/race. And it's the simplest to use :)

Solutions in my mind;

Update race can be addressed with optimistic locking just like publish with headers (i.e. Nats-Expected-Last-xxx). When asking for config, also receive that configs seqno(timestamd/token and optionally ref it in update request to make it fail if another update has been done since the config was read.

I am actually happy with a Create that errors out (including as a result the existing info) so that an Update can be called instead

**Comment by piotrpio** [comment]
I completely agree with you! Operations on streams are indeed idempotent, so there is no issue. For consumers, we did not want to introduce additional complexity on the client (more RTTs to the server), because creating consumers should be as cheap as possible. That's why proper create and update operations (idempotent create and update which fails if consumer does not exist) will be added to the server soon (probably in next minor release). That's when we'll add `CreateConsumer()` and `UpdateConsumer()`.
