### ISSUE TITLE
New Jetstream CreateOrUpdateConsumer ignores FilterSubjects configuration field

### ISSUE THREAD

**Issue by juhahyvarinen** [nats-io/nats.go#1324]
It seems that `FilterSubjects []string` field in `ConsumerConfig` is silently ignored when new consumer is created by `CreateOrUpdateConsumer` function. Is that a bug or what is the reasoning behind that?

**Comment by piotrpio** [comment]
@juhahyvarinen thanks for creating the issue! Multiple filter subjects is a feature which will be introduced in nats-server@2.10.0, so until it's released a single `FilterSubject` has to be used. Client code should denote this though, I will add a proper comment.

**Comment by Jarema** [comment]
If you want to play today with 2.10 features, like consumers with multiple filters, check out the new nightly nats-server docker images or the `dev` branch of the nast-server repo.

**Comment by tpihl** [comment]
@piotrpio What is the thinking with backward compatibility (since 2.10 isn't a breaking change) and the jetstream client need to support all 2.x.x versions (non-breaking changes)

Shouldn't the new jetstream only expose FilterSubjects?

And since the server-change is non-breaking, doesn't the jetstream client need to compensate for when the server cannot handle multiple filters? 
* One way ( a bad way) would be to widen the filter and drop subjects outside the requested filters client-side.
* Another way (not sure how to do) would be to create multiple single-filter-consumers and combine/sort in the client.

Or is this a breaking change that need a v2 client and a v3 server?

**Comment by tpihl** [comment]
@piotrpio Hi, I would respectfully disagree that this solves the longterm issue of a breaking change that is not managed.
