### ISSUE TITLE
Conn.publish can result in "short write" Error when writing to buffer

### ISSUE THREAD

**Issue by longsleep** [nats-io/nats.go#174]
I am not sure what actually is causing it, but i sometimes see the NATS connection fail and the reason is that the Write functions in https://github.com/nats-io/nats/blob/master/nats.go#L1668 error with "short write". In such a state the NATS connection is essentially broken as for some reason the underlaying TCP connection is dead.

It just appens, sometimes even directly after creating the connection, somtimes later after feeding a bunch of Publish calls to the connection through a channel.

Any idea what could cause this?

**Comment by derekcollison** [comment]
Do you have any example code to reproduce? I will take a look regardless.

**Comment by derekcollison** [comment]
Looks like it can only come from the write to the underlying socket.

https://golang.org/pkg/bufio/#Writer.Write
https://golang.org/src/bufio/bufio.go?s=14841:14893#L578

**Comment by longsleep** [comment]
Yes it comes from the underlying socket. I do not know why it happens (connected to 127.0.0.1:4222 on Linux).  

Is there any chance the NATS connection could recover there?

Reconnecting (by restarting gnatsd) gets detected properly, but the outbound publish buffer is still broken and will raise the error forever.

I do not have a easy to use example, but i am working on https://github.com/longsleep/spreed-webrtc/blob/pipeline-support/go/channelling/bus_manager.go#L263 - the Write function there is called from many places and multiple Go routines. I reviewed it and did not find any issue obvious to me.

**Comment by derekcollison** [comment]
I will take a c loser look and see if there is a better way we can handle the situation. Thanks for the feedback.

**Comment by kozlovic** [comment]
I may be wrong, but I think the problem is the way the code used to create the nats connection. They are returning a copy of the nats connection: https://github.com/strukturag/spreed-webrtc/blob/v0.25.2/go/natsconnection/natsconnection.go#L58
They store in Connection, a nats.Conn, so they do the above, but I don't think this is correct. They should simply store a *nats.Conn and return nc.

**Comment by longsleep** [comment]
@kozlovic that certainly needed fixing. But not sure how this it could be related. I changed this in https://github.com/longsleep/spreed-webrtc/commit/86fd0e49d21db4312d409a6a3a80e0ca00a5416a - if you are right the problem might not appear any more.

**Comment by ColinSullivan1** [comment]
To back up Ivan's comment, in my experience, short write errors have been a symptom of creating a copy of the NATS connection.

**Comment by longsleep** [comment]
Ok, lets see if it start to happen again when no longer creating a copy. I will either close or report back probably tomorrow. Thanks all for you help so far!

**Comment by derekcollison** [comment]
I should have made it an interface.. Maybe for 2.0

**Comment by longsleep** [comment]
Not creating a copy of the nats connection indeed seems to have resolved the issue and i did not see any "short write" errors since. 

I leave it to you folks to close this issue as i still think that the behavior if there is a "short write" could be improved.

**Comment by kozlovic** [comment]
I am closing because if you look at `bufio.go`, once `Write()` encounters an error, that error is saved in the `Writer` structure. The error is checked at the beginning of the `Write()` call, and if not nil, that error is returned. In other words, there would be no way to recover from an error, "short write" or not.

```
type Writer struct {
	err error
	buf []byte
	n   int
	wr  io.Writer
}

func (b *Writer) Write(p []byte) (nn int, err error) {
	for len(p) > b.Available() && b.err == nil {
           (...)
	}
	if b.err != nil {
		return nn, b.err
	}
```

**Comment by prydin** [comment]
Requesting reopening.

I encountered this when writing very aggressively to a socket through a BufferedWriter on a Linux system. I don't think this should be returning an error at all. It is perfectly OK for the underlying device driver to write only a partial chunk of data when it's running low on buffer space, for example. That's why the write()-primitive on most OSes returns a number of bytes actually written. 

Instead of returning an error, copyBuffer should advance the start of the slice it's writing "nw" steps and try again. Here's an example that illustrates the proposed algorithm:

https://play.golang.org/p/buQ-2TcOvHi

**Comment by derekcollison** [comment]
This still need attention?

**Comment by longsleep** [comment]
I think so.

**Comment by derekcollison** [comment]
ok do you have an example that can reproduce at all?

**Comment by derekcollison** [comment]
Looking to see if we have a solution here, any updates?

**Comment by longsleep** [comment]
No reproducer sorry - I do not have the time right now to work on any. Closing it - I will reopen once I have the time to look.
