### ISSUE TITLE
Should Connect return errors if it cannot connect?

### ISSUE THREAD

**Issue by tomwilkie** [nats-io/nats.go#195]
Currently, the client 'constructor' (`nats.Connect`) will return `nil, err` if it can't connect to NATS.  This behaviour puts a strict ordering on the start up sequences of my services; the NATS client is effectively instantiated in my `main()` function, such that the service cannot start if it can't contact NATS.  However my service are able to tolerate NATS not being there, and degrade gracefully - as message delivery is at most once, I kinda don't care too much if it fails.

My preference would be for connection state to be completely internal; client creation should only fail it it is passed a malformed url, for example.  The client should try to connect asynchronously in the background, failing requests until it does - the service not being there is just another failure case to me. I believe this is just a special case of the NATS coming and going, which you already have code to deal with.  This seems like something the client library should do - I can't be the first person to hit this.

(As a side note, I actually don't have control over the order in which services are started; its not needed by anything else; the golang SQL client libraries and the AWS libraries all behave in my desired way)

**Comment by derekcollison** [comment]
I will take a look. In general, yes, I felt you should need to connect to a server at least once before a connection could be returned. We buffer messages while disconnected for some period of time until we hit limits, and we could re-use this logic. But we also have others pointing out that they do not want this behavior, and that they want the ability to control this behavior, or at least have a ttl.

**Comment by Zambiorix** [comment]
Is there any progress on this one?
I'm also want to leave the connection status internal.

I'm also using Aerospike DB and they have the same behaviour for client startup.
But they also have an option "FailIfNotConnected" that you can set/unset.

Can go-nats use the same approach? Offer an option to turn off connection failure at startup?
Once it is running, it'll connect/reconnect when servers are available ..

Should be fairly trivial to implement, not?

Thanks
Cheers

Gerd

**Comment by mcqueary** [comment]
Hi @tomwilkie @Zambiorix We rarely view a fundamental behavior change as trivial :) At a minimum, I suspect it would introduce new failure scenarios that we'd need to test for. Additionally, for consistency, we'd want to implement it across all clients we support. 

We're undertaking a new round of roadmap planning and review over the next few weeks and will discuss further as part of that.

**Comment by kekoav** [comment]
I would also like to see retries on `Connect()` to allow for some intermittent network failures to not fail the whole system(or have to implement my own retry logic on background). There is already support for "Reconnect" when servers become unreachable. This is configured through the options `MaxReconnect`, `ReconnectWait`, `ReconnectedCB` and `Timeout`.

The reconnection logic appears to work well. Could that functionality be reused at initial connect time if users opt-in to this behavior? 

As a naive new user, I honestly assumed Reconnection would handle the initial connect as well, and was surprised that it only referred to connection failures after the initial connect.

I would suggest not changing the old way for use cases where a connection failure should stop the whole system, but for many systems intermittent failures should be recoverable, even at system startup (initial connection) time. I think the existing reconnection machinery gives me enough flexibility to respond to connection issues(through the `ReconnectedCB` and `DisconnectedCB` handlers).

I would not expect buffering in this situation. I think in the initial connection case it would be fine to fail any subscribes/publishes instead of transparently buffering. I'm not even sure I'd like buffering in the reconnection case, but I see this can be controlled with `ReconnectBufSize`.

**Comment by derekcollison** [comment]
Yes this is a reasonable request and could be introduced in a backward compatible way as a new option to the Connect() call.

**Comment by mnarrell** [comment]
Has there been any progress on this issue?

**Comment by derekcollison** [comment]
Wally and Jaime, could you both take a look?

**Comment by serajam** [comment]
Need this feature

**Comment by kozlovic** [comment]
What is the consensus here? I get that we would add a new option so that we don't change the default behavior, but is the initial Connect() blocking and using max reconnects/wait if there is a failure? Or do we want the Connect() to return although not connected?
For instance, in the C client I have added the ability to retry the initial connect, but the Connect call will block until it can connect or exhausts the number of connect attempts.

**Comment by derekcollison** [comment]
Yes I think we add new option and return a connection that is in the reconnecting state right away if it can't connect to a server in the initial set.

**Comment by hbobenicio** [comment]
In my case, coming from #310 and I hoped for some automatic Connect retries, as it's already an Option (nats.ReconnectWait and nats.MaxReconnects).

Unfortunatelly, it won't retry for the first connect right?

This is the boilerplate I need to do now if I want reconnections at the first attempt (hope It would be useful):

```golang
	servers := []string{ "nats://localhost:4222" }
	maxReconnects := 60
	reconnectWait := 2 * time.Second
	natsOpts := []nats.Option{
		nats.MaxReconnects(maxReconnects),
		nats.ReconnectWait(reconnectWait),
	}
	var natsConn *nats.Conn
	var err error
	for i := 0; i < maxReconnects; i++ {
		log.Println("info: nats: trying to connect to servers...")
		natsConn, err = nats.Connect(strings.Join(servers, ","), natsOpts...)
		if err == nil {
			log.Println("info: nats: connected.")
			break
		}
		log.Println("warn: nats: connection failed:", err)
		log.Printf("info: sleeping for %v for next attempt [%d/%d]\n", reconnectWait, i+1, maxReconnects)
		time.Sleep(reconnectWait)
	}
	if err != nil {
		log.Fatalf("error: nats: connect: couldn't connect after %d retries: %v\n", maxReconnects, err)
	}
	defer natsConn.Close()
```

Quite a lot, right? (Context API not covered)

In order to prevent this boilerplate from users and keep the default behaviour and backwards compatibility maybe some new bool option like `nats.ReconnectOnFirstAttempt` could handle it.

IMHO, the most intuitive and expected default behaviour though is to use `nats.MaxReconnects`consistent even on first attempt. If it's set to 60, then why returning an error before retrying 60 times? There is `nats.ReconnectHandler` Option already if you need to do something beetween attempts. If you want failure if couldn't connect, set MaxReconnects to 0.

**Comment by kozlovic** [comment]
Based on comments above, it sounds like the consensus is to trigger the behavior with a new option to maintain backward compatibility. I am sorry that I still did not get to do this. Will bump it to my list of TODOs.
