### ISSUE TITLE
No mention of NGS URL

### ISSUE THREAD

**Issue by variadico** [nats-io/nats.go#510]
I'm running through the NGS tutorial, but couldn't find the NGS URL. I tried looking in this repo, but didn't see any mention of it. I eventually did find it, but then I started wondering...

Should we mention the URL somewhere here? Maybe even have a variable for it, like `nats.DefaultURL`, but instead `nats.NGS`.

That way we get:

```
nats.Connect(nats.NGS, nats.UserCredentials("user.creds"))
```

**Comment by sasbury** [comment]
it does show up on https://synadia.com/ngs/how-it-works, but agreed it should be in those examples and perhaps mentioned earlier!

**Comment by sasbury** [comment]
I am working on some changes to the site, maybe i can fix this with those

**Comment by variadico** [comment]
Yep. You're totally right. I got stuck here https://synadia.com/ngs/signup because I was trying to get that example command to work, but that page doesn't mention what `url` is.

**Comment by aricart** [comment]
It is actually there, but hidden and worse - at least for me it is a
non-intuitive and hard to remember. The service is called ngs, but the
operator is called synadia, the website is synadia.com, internally we use
synadia.io for jwt resolution (which is exposed). Finally, the service URL
is `connect.ngs.global` which is made harder because of the 'connect'
hostname and the 'global' top level domain.
