### ISSUE TITLE
Race Condition between processMsg() and Stats()

### ISSUE THREAD

**Issue by Will2817** [nats-io/nats.go#520]
Client version: 1.8.1

The following race condition occurred while trying to call the `Stats` function while a message was being processed. Note the `Stats` function call in the test that produced this, was being called from a go routine to periodically scrap the NATS client stats.
```
WARNING: DATA RACE
Write at 0x00c000254000 by goroutine 48:
  github.com/******/******/vendor/github.com/nats-io/nats%2ego.(*Conn).processMsg()
      /go/src/******/******/vendor/github.com/nats-io/nats.go/nats.go:2083 +0xb3
  github.com/******/******/vendor/github.com/nats-io/nats%2ego.(*Conn).parse()
      /go/src/github.com/******/******/vendor/github.com/nats-io/nats.go/parser.go:177 +0x2c05
  github.com/******/******/vendor/github.com/nats-io/nats%2ego.(*Conn).readLoop()
      /go/src/github.com/******/******/vendor/github.com/nats-io/nats.go/nats.go:1983 +0x59e

Previous read at 0x00c000254000 by goroutine 60:
  github.com/******/******/vendor/github.com/nats-io/nats%2ego.(*Conn).Stats()
      /go/src/github.com/******/******/vendor/github.com/nats-io/nats.go/nats.go:3712 +0xbf
  github.com/******/******/vendor/github.com/******/******/******.(*Client).natsStatsMonitor()
      /go/src/github.com/******/******/vendor/github.com/******/******/******/conn.go:43 +0x209
```

I believe https://github.com/nats-io/nats.go/blob/master/nats.go#L2164-L2168 is using a Read only lock while it is doing an update to `nc.InBytes` and `nc.InMsgs`, when it should be a Write lock as well.

**Comment by andriy-bulynko** [comment]
Please correct me if I'm wrong @Will2817, but I think the client version may have been 1.7.2.

**Comment by kozlovic** [comment]
Based on the stack, this is not the latest, but I can reproduce the race with the latest too. He is right that nc.InMsgs is incremented under subsMu.RLock() while Stats() is also checking it with the same readlock, which means that they both can execute in parallel.
The unconventional move may be to actually have Stats() get the write lock, and leave the RLock in processMsg()...

**Comment by kozlovic** [comment]
The original intent of `nc.subsMu` was to avoid getting the connection's lock in processMsg() just to lookup the subscription from the map. But the side effect is that since there is no connection's lock here, we still needed to protect nc.InMsgs in Stats(), so this is why I grab the lock (along with nc.mu.Lock()) in there.
Switching processMsg() nc.subsMu to write lock causes 5% perf drop in my test. Leaving as rlock but have Stats() require nc.subsMu.Lock() (writeLock) maintains the original perf and prevents the race (since processMsg() won't execute the inMsgs++ if under subsMu write lock in Stats().
