### ISSUE TITLE
Document thread-safety

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats.go#532]
Given https://github.com/nats-io/nats.go/blob/master/nats.go#L2550, I assume that the exported functions on https://godoc.org/github.com/nats-io/nats.go#Conn are thread-safe. How about documenting that? I had a case here where I wasn't sure if I could share a nats Conn between goroutines.

**Comment by derekcollison** [comment]
Yep that is reasonable.

**Comment by kozlovic** [comment]
You already reported that we should document thread-safety in https://github.com/nats-io/nats.go/issues/459. We did add that to the Conn struct: https://godoc.org/github.com/nats-io/nats.go#Conn
```
The connection is safe to use in multiple Go routines concurrently.
```
Since I am planning to do the same for the streaming client (since you have opened an issue there too), is that not enough? I don't think it makes sense to doc *all* methods if we state that the connection object is "thread-safe".

**Comment by JensRantil** [comment]
I'm really sorry. I totally missed that. I searched for "thread" in the documentation and skimmed the text. Clearly missed this part.

**Comment by JensRantil** [comment]
...and yes, I have the memory of a goldfish!
