### ISSUE TITLE
Response is sent even timout happen on Request side 

### ISSUE THREAD

**Issue by Galileon** [nats-io/nats.go#533]
hello, I have some issue. Trying to make at last one delivery and confirm pattern using Nats. Teoretically everything looks ok but in scenario when Request timeout is shorter than message processing before reply it ends with timeout and message reply then is being sent without any issue. 

Please check attaches simple code to illustrate this behaviour. I know its related to how reply works but meybe it is worth to consider changing something there to throw exception on reply for expired request taks ? 

[Program.txt](https://github.com/nats-io/nats.go/files/3898320/Program.txt)

**Comment by kozlovic** [comment]
Your program seem to be .NET, and this is Go client library repo, but that's ok since this is not an issue with any library. What you are asking is impossible since the library does not know about interest. Only the server does. Also, publish calls are asynchronous, meaning that there would be no way for the library to throw an exception because the library is not waiting in any feedback from the server for a given publish message.
In NATS, publishers and subscribers are completely de-coupled. 

Your requestor will get a timeout, and it could try to resend the request. What would need to happen is that your responders need to be able to detect that the job was already done. Of course, that is easier say than done, since as soon as you would have multiple consumers, the information about a task being already processed need to be distributed. The alternative (which is somehow similar) is to make the processing of a task idempotent.

**Comment by Galileon** [comment]
hi, yes i thougth like that. Thank U.
