### ISSUE TITLE
About websocket

### ISSUE THREAD

**Issue by Leadrive** [nats-io/nats.go#619]
Hi, I use github.com\orus-io\nats-websocket-gw
to make a nats websocket server.
and use websocket-nats to test it, it work ok.
````golang
package main

import (
	"net/http"

	gw "github.com/orus-io/nats-websocket-gw"
)

func main() {
	gateway := gw.NewGateway(gw.Settings{
		NatsAddr: "localhost:4222",
		Trace:    true,
	})
	http.HandleFunc("/", gateway.Handler)
	http.ListenAndServe("0.0.0.0:4223", nil)
}
````
But if use go-nats+websocket，the received message will have the leader four bytes. [129, 126, 1, 34]
maybe is FIN, RSV1, RSV2, RSV3?

```` golang
package main

import (
	"flag"
	"log"
	"net"
	"net/url"
	"runtime"
	"time"

	nats "github.com/nats-io/nats.go"

	"github.com/gorilla/websocket"
)

var (
	flagURL = flag.String("to", "wss://www.xxx.com/wsnats", "host to connect")
	flagUser = flag.String("nats-user", "", "nats user")
	flagPass = flag.String("nats-pass", "", "nats password")
)

type customDialer struct{}

func (cd *customDialer) Dial(network, address string) (net.Conn, error) {
	u, _ := url.Parse(*flagURL)
	c, _, err := websocket.DefaultDialer.Dial(u.String(), nil)
	if err != nil {
		return nil, err
	}
	return c.UnderlyingConn(), nil
}

func main() {
	flag.Parse()

	opts := []nats.Option{
		nats.SetCustomDialer(&customDialer{}),
		nats.ReconnectWait(1 * time.Second),
	}

	if *flagUser != "" {
		if *flagPass == "" {
			opts = append(opts, nats.Token(*flagUser))
		} else {
			opts = append(opts, nats.UserInfo(*flagUser, *flagPass))
		}
	}

	nc, err := nats.Connect(*flagURL, opts...)
	if err != nil {
		panic(err)
	}

	nc.Subscribe("foo", func(msg *nats.Msg) {
		log.Printf("%s", msg.Data)
	})

	go func() {
		for {
			nc.Publish("foo", []byte("test message"))
			time.Sleep(5000 * time.Millisecond)
		}
	}()

	runtime.Goexit()
}
````

How to fix the send and receive message?

**Comment by Leadrive** [comment]
I use nignx to redirect 4223 port to /wsnats

**Comment by kozlovic** [comment]
@Leadrive Please note that NATS Server in the main branch has native support for Websocket frames. As mentioned, it is available if you build from the NATS Server main branch (https://github.com/nats-io/nats-server) or use our nightly builds (docker pull synadia/nats-server:nightly).

That being said, the Go client does not have Websocket support. For now, only the Node client has websocket support (https://github.com/nats-io/nats.ws).

Are you saying that you got the failure when you tried to use the proxy against a NATS Server running with websocket support? If so, again, this is expected because you are simply using gorilla's websocket library to create the connection, but then nothing makes the NATS library convert the NATS protocol into websocket frames. 
So if you want to connect directly to the NATS Server's websocket port and use the Go client, you would need some sort of proxy that speaks websocket when connecting to NATS server and plain when talking to the NATS library. But before going further, I want to make sure I understand exactly what the issue is.

**Comment by Leadrive** [comment]
Because the main nats-server(support websocket) message frames different of the gateway proxy mode.
https://github.com/isobit/websocket-nats does not support the newest nats-server now.

And https://github.com/nats-io/nats.go does not support now.

Yes, the (https://github.com/nats-io/nats.ws) support it. but it base on Node

**Comment by kozlovic** [comment]
It has been asked to provide support for Websocket in the NATS Go client, but this is not available at the moment. In the meantime, you can always use the proxies and connect to the non websocket port of the NATS server.
