### ISSUE TITLE
Return error if actual consumer configuration is different

### ISSUE THREAD

**Issue by kszafran** [nats-io/nats.go#796]
## Feature Request

When creating subscriptions I can pass extra options, e.g.:
```go
sub, err := js.PullSubscribe("TEST.*", "testing", nats.MaxDeliver(3))
```
The consumer is created in NATS if it didn't exist yet:
```
$ nats con info TEST testing
Information for Consumer TEST > testing created 2021-08-17T11:37:10+02:00

Configuration:

        Durable Name: testing
           Pull Mode: true
      Filter Subject: TEST.*
         Deliver All: true
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 3
     Max Ack Pending: 20,000
   Max Waiting Pulls: 512

State:
...
```

If I then change the options, e.g.:
```go
sub, err := js.PullSubscribe("TEST.*", "testing", nats.MaxDeliver(5))
```
Then the new value is silently ignored and the consumer still has `Maximum Deliveries: 3`. The options seems to be used only when creating a new consumer, but ignored otherwise (some of them at least).

While it might not be feasible to transparently update the consumer, I would expect to get an error telling me that the requested options do not match the actual consumer configuration.

#### Use Case:

I can very easily imagine a situation where a developer changes the options (adds a new one, removes one, changes a value) thinking that it will work. For someone unfamiliar with NATS JS it's not obvious that some consumer object exists in NATS itself and that these options are not just client-side connection options. It's easy for the code to diverge from the actual configuration.

#### Proposed Change:

Compare the actual consumer configuration with the requested one an return an error if there's a mismatch.

It seems that the existing configuration is already read (the `info` variable), so this shouldn't affect performance.

#### Who Benefits From The Change(s)?

Unwitting developers trying to change the consumer configuration.

#### Alternative Approaches

Update the consumer configuration to match the requested one.

**Comment by kozlovic** [comment]
This is going to be difficult, because we can't simply compare the consumer config returned with the library's consumer config version, because the user may not have set everything and in that case, the server uses some default. The client library would have to make sure to catalog all fields default values and the server would never be able to change those, or add new fields, otherwise clients would break (at least if we were to use a generic reflect.DeepEqual).
Wondering what others @derekcollison, @wallyqs think about that...

**Comment by ripienaar** [comment]
Realistically speaking the server-set default values are part of the API. We cannot just change them since it can change client code behavior.

**Comment by kozlovic** [comment]
I disagree. What if the server decides that if no AckWait is specified, instead of defaulting to 30 seconds, it now defaults to 10s (or any other numbers). That would break the equality check if libraries are not changed at the same time.
Right now, the Go client doesn't even set a value for AckWait (if the user did not set one), therefore it has AckWait==0, send this way, and the server uses whatever default it wants. It is the same for other fields...

**Comment by kozlovic** [comment]
I deleted a comment I made, which made no sense, since it was based on the current behavior that the client does not set any default. As long as the client library describes which default is used, I guess it is ok.

**Comment by ripienaar** [comment]
I captured the server defaults in the schemas and iirc the CLI actually send those defaults.

100% though, changes to defaults are API breaking changes. You might find the odd one where its not, but its better to say as a general rule these defaults are API, thats the same approach.

**Comment by wallyqs** [comment]
It is going to require a few changes but would be simpler to implement if we change the client to set all the defaults as defined in the API so that it is not ambiguous as in the natscli.

For example, calling first `js.SubscribeSync("test", nats.Durable("dur"))` will create a consumer but leave AckWait unitialized as `0s` which then becomes [30 secs](https://github.com/nats-io/nats-server/blob/8cda9461731e800e58a91b558fdb346fbe55457c/server/consumer.go#L256) but when you lookup the consumer config it would show as being `0s`.

This means that when it is called explicitly with using the right default for example:

```
js.SubscribeSync("test", nats.Durable("dur"), nats.AckWait(30*time.Second))
```

Although technically the ack wait is the same since it is the same default as in the server, from the client side cannot tell since the consumer config is presented to the client as `0s`.

**Comment by kozlovic** [comment]
@wallyqs Sorry, I was going to let you know that I started looking into this. My plan is to have a "checkConfig" function that will ignore user settings that are not set, and otherwise compare. For instance: `u.AckWait > 0 && u.AckWait != s.AckWait`, with `u` the user config and `s` the "server" config. Will do that for all fields that need checking (since some don't, like DeliverSubject, etc..).

**Comment by ripienaar** [comment]
What is ambiguous in the CLI? I do set defaults but guess I missed a few. Intention was setting the defaults.

**Comment by wallyqs** [comment]
yes I meant to say that the natscli is not ambiguous since the defaults are set.

**Comment by kozlovic** [comment]
> I captured the server defaults in the schemas

Is it this file? https://github.com/nats-io/jsm.go/blob/main/schemas/jetstream/api/v1/consumer_create_request.json
I see only 1 default for `max_waiting`, so that must not be it.

**Comment by wallyqs** [comment]
`max_waiting` is 512 in the schema, though `ack_wait` does not include the default (30 secs).

https://github.com/nats-io/jsm.go/blob/main/schemas/jetstream/api/v1/consumer_create_request.json#L200
https://github.com/nats-io/jsm.go/blob/main/schemas/jetstream/api/v1/consumer_create_request.json#L147

**Comment by ripienaar** [comment]
Ok, I guess early schemas are lacking. 

Have to go through server code. Would you mind also sending a list of defaults and I will go through capturing that in them.

**Comment by kozlovic** [comment]
@ripienaar I am confused, you say that you will have to go through server code but ask me to send a list of defaults?

For this specific issue, I am convincing myself that the right approach is what I discussed before, that is, if users don't specify a specific configuration value, then that means they don't care about it (but of course, one could argue that they know what is the default value is being assigned by the server, so they don't specify it, but *I* would argue that this is bad practice since it makes the user rely on the server keeping this value and never change it). So the configuration check routine needs to take into account only what was set by the user and compare to what is returned.

I will again take the example of AckWait. Suppose users create JS subscriptions but don't specify this value in their app, that really means they don't know or care about it. The server currently picks 30sec. What if in the future we realize that default should 15sec or 45sec? Making defaults in the library will always have to be in par with the server and I am telling you, there will be situations where the server will decide to change a default and that will break all existing libraries, for something that the user did not even care about since the configuration field was not even set when creating the subscription.

Not sure if this is the case, but there could be situations where a given configuration field has different "default" value based on some other configuration setting.

**Comment by kszafran** [comment]
That makes sense in my opinion. Only those values that are specified explicitly need to be checked against the actual consumer config. If I don't specify AckWait, it means that I don't care about a specific value. On the other hand, if I do specify AckWait=10s, then I expect that this value will be used and an error would be helpful if a consumer has already been created with a different value.

**Comment by ripienaar** [comment]
I meant we have to go through the server source and if someone does - please send a list else I will. 

The ackwait example to me is a good example of the opposite. If we set it to 30 by default and it’s fine for a user kind of by accident - easy to miss - if we change the default users might find increased times when they hit redeliveries. Of course users should know what they are doing - but the reality is new users don’t and we want to minimise traps and land mines.

**Comment by kozlovic** [comment]
Anyway, since some of the config params have been made enums that start at 0 in the library, I have no way to know (unless I were to change those enums to start at 1) if the user intent was to set them or not, and same issues with boolean flags.
So I guess we will indeed need to take the approach of setting the baseline configuration base on defaults, user option will overwrite and then do comparison of baseline+user with info we get from server.
Will work on that next week.

**Comment by ripienaar** [comment]
Will gather defaults next week and update schemas.

**Comment by ripienaar** [comment]
I've added some defaults in https://github.com/nats-io/jsm.go/pull/320

**Comment by kozlovic** [comment]
@ripienaar Please have a look at the PR description and the reasons why I went this route. I tried setting defaults but it would not work (for instance, it happens that AckWait is a default of 30 sec in the server, but depends on the AckPolicy (meaning that it is set only for AckExplicit and AckAll)). But even that did not cover the cases where the user simply does not set any option to configure and should not be penalized because the incoming consumer config does not match.

The telling example I am using is "description". If the consumer is created with a description, why fail a "js.Susbcribe()" call just because user does not provide the option to set the description to match the one that was used to create it?

I believe that the implementation of the PR matches the original poster's (@kszafran)  requirement. Hopefully I can convince you.
