### ISSUE TITLE
Purge stream problem

### ISSUE THREAD

**Issue by ali-a-a** [nats-io/nats.go#909]
This is my sample code:

```go

func (jetStream JetStream) Run() {
	_, err := jetStream.js.AddStream(&natsio.StreamConfig{
		Name:     "stream",
		Subjects: []string{"stream.test"},
	})
	if err != nil {
		logrus.Errorf("failed to add new stream: %s", err)
	}

	_, err = jetStream.js.Subscribe("stream.test", func(msg *natsio.Msg) {
		time.Sleep(5000 * time.Millisecond)

		err := msg.Ack()
		if err != nil {
			logrus.Errorf("failed to ack message: %s", err)
		}

		logrus.Infof("received a JetStream message: %s", string(msg.Data))
	})

	go func() {
		i := 0
		for range time.Tick(500 * time.Millisecond) {
			i++
			_, err := jetStream.js.Publish("stream.test", []byte(fmt.Sprintf("data %d", i)))
			if err != nil {
				logrus.Errorf("failed to publish: %s", err)
			} else {
				logrus.Infof("%d is published successfully", i)
			}
		}
	}()

	go func() {
		for range time.Tick(7000 * time.Millisecond) {
			err := jetStream.js.PurgeStream("stream")
			if err != nil {
				logrus.Errorf("failed to purge %s: %s", "stream", err)
			} else {
				logrus.Infof("stream %s is purged successfully", "stream")
			}
		}
	}()
}

```

and this is the output:

```
INFO[0000] 1 is published successfully                  
INFO[0001] 2 is published successfully                  
INFO[0001] 3 is published successfully                  
INFO[0002] 4 is published successfully                  
INFO[0002] 5 is published successfully                  
INFO[0003] 6 is published successfully                  
INFO[0003] 7 is published successfully                  
INFO[0004] 8 is published successfully                  
INFO[0004] 9 is published successfully                  
INFO[0005] 10 is published successfully                 
INFO[0005] 11 is published successfully                 
INFO[0005] received a JetStream message: data 1         
INFO[0006] 12 is published successfully                 
INFO[0006] 13 is published successfully                 
INFO[0007] 14 is published successfully                 
INFO[0007] stream stream is purged successfully         
INFO[0007] 15 is published successfully                 
INFO[0008] 16 is published successfully                 
INFO[0008] 17 is published successfully                 
INFO[0009] 18 is published successfully                 
INFO[0009] 19 is published successfully                 
INFO[0010] 20 is published successfully                 
INFO[0010] 21 is published successfully                 
INFO[0010] received a JetStream message: data 2         
INFO[0011] 22 is published successfully                 
INFO[0011] 23 is published successfully
```
My problem is receiving `data 2` while we purged the stream before.

Is this an expected behavior? Could I purge on a push mode subscription?

Many thanks

**Comment by kozlovic** [comment]
The stream was purged after the data 2 was actually published, so the server already sent that message to the client library. It's just that your callback intentionally took 5 seconds to process the first one.

If you are trying to drain the subscription, then maybe use Drain() instead? But not sure exactly what you are trying to do or what are your requirements.

**Comment by ali-a-a** [comment]
Actually, I need this for some cases that some invalid messages were published, and I have to remove them. So, I could purge the stream, and I expect my subscriber won't process them later. But, I need to process new messages which were published after the purge process. I think Drain() won't help in this situation since it removes interest.

**Comment by kozlovic** [comment]
@ali-a-a Regarding Drain(), like I said, I wasn't sure what you requirements were. 

So again, I want you to understand that the library may receive in the background messages for the JS consumer. The fact that the message callback is invoked with 1 message at a time and that the callback can take time to process individual messages means that it is possible that there are messages waiting to be dispatched inside the library.
When you issue the purge, you remove the messages that are pending/waiting for ack in the server side, but that does not magically remove them from the library's internal queue.

The approaches I would suggest:
- Have your application be able to recognize that a message is bad and cannot be processed. Depending of the JS consumer's Ack mode, if your application needs to ack, there is the msg.Term() option that says: "I can't process this message, and nobody can, so be done with that message"
- If you can't do that, and want to limit the number of "inflight" messages from the server to the client library, you would need to reduce the MaxAckPending to 1, so that only 1 message at a time is sent to a client. But again, it is very possible that as you are issuing a Purge(), the message was being sent to the client and so your application code would still need what to do with a "bad" message.

**Comment by ali-a-a** [comment]
I got your points, and it seems my expectation was false. I'll try your suggestions and find the best fit solution for my requirements. Thanks for your help.
